#--------------------------------------------
# INSTRUCTION
# Quoted strings are to be filled in by student
#

clean:
	rm -f ".o files" ".out files" core ".exe/class files" "outputs"
	rm -f *.out
	rm -f *~
	rm -f *.pyc
	ls
